### ISSUE TITLE
ORES wp10 endpoint sometimes returns a float instead of score probabilities

### ISSUE THREAD

**Issue by ragesoss** [wiki-ai/ores#109] opened 2015-12-09 17:30 UTC
I've gotten occasional error logs while handling data gotten from ores. In particular, after parsing the json into a ruby hash and then getting the data for a particular revision from that hash, the routine checks whether the key 'probability' is present in that revision's data. But instead of being a hash, that data is a float.

Here's the error:
```
lib/importers/revision_score_importer.rb in block in save_scores at line 64
NoMethodError: undefined method `key?' for 1443972475.2339349:Float
```

Here's the routine that ingests ores data: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/lib/importers/revision_score_importer.rb

This only seems to happen every once in a while, and our system gathers revision scores for every revision in the system... so the same revisions that cause an error one time seem to be working fine on subsequent attempts.

**Comment by halfak** [comment] 2015-12-09 18:28
It would be helpful if I could have the exact output from ORES.  Could you capture this output before you do any parsing so that we can examine it the next time an error occurs?

**Comment by halfak** [comment] 2015-12-09 18:29
FYI, it looks like this is a timestamp that translates to `Sun, 04 Oct 2015 15:27:55 GMT`

**Comment by halfak** [comment] 2016-03-09 21:28
@ragesoss, can you confirm that this is still happening?

**Comment by halfak** [comment] 2016-03-23 15:56
I'm going to close this since I can't reproduce and there was no confirmation of the issue.  Please re-open if it is still a problem.

**Closed by halfak** 2016-03-23 15:56 UTC
Labels: bug

**Comment by ragesoss** [comment] 2016-03-23 16:42
Sorry, I missed this the first time. I don't think it's happening anymore.
